import {
  App,
  ApplicationSearchPayload,
  Comment,
  CommentsResponse,
  History,
  Response,
  ViewAppsListResponse,
  ViewApplicationsResponseAssignedGroup,
} from '../../@types/managingAppsApi'
import { InmateDetail } from '../../@types/prisonApi'
import { APPLICATION_STATUS } from '../../constants/applicationStatus'
import { BaseUser } from '../../interfaces/hmppsUser'

export default class TestData {
  app: App = {
    id: '13d2c453-be11-44a8-9861-21fd8ae6e911',
    reference: '1232143',
    genericForm: false,
    assignedGroup: {
      id: '591185f2-863a-4a32-9812-c12f40b94ccb',
      name: 'Business Hub',
      establishment: {
        id: 'TEST_ESTABLISHMENT_FIRST',
        name: 'ESTABLISHMENT_NAME_1',
        appTypes: [
          'PIN_PHONE_ADD_NEW_SOCIAL_CONTACT',
          'PIN_PHONE_ADD_NEW_OFFICIAL_CONTACT',
          'PIN_PHONE_CREDIT_SWAP_VISITING_ORDERS',
          'PIN_PHONE_SUPPLY_LIST_OF_CONTACTS',
          'PIN_PHONE_REMOVE_CONTACT',
          'PIN_PHONE_EMERGENCY_CREDIT_TOP_UP',
        ],
        defaultDepartments: false,
        blacklistedAppGroups: [],
        blacklistedAppTypes: [],
      },
      initialApp: 1,
      type: 'DEPARTMENT',
    },
    appType: 'PIN_PHONE_CREDIT_SWAP_VISITING_ORDERS',
    applicationType: {
      id: 3,
      name: 'Swap visiting orders (VOs) for PIN credit',
    },
    applicationGroup: {
      id: 1,
      name: 'BT PIN PHONES',
    },
    requestedBy: {
      username: 'G123456',
      userId: 'cb42921f-3b33-4efa-a873-4a1d86eb6caa',
      firstName: 'Emily',
      lastName: 'Brown',
      category: 'PRISONER',
      cellLocation: 'A-0-123',
      location: 'Preston (HMP)',
      iep: 'Enhanced',
    },
    createdDate: '2024-09-15T00:00:00Z',
    createdBy: 'cb42921f-3b33-4efa-a873-4a1d86eb6caa',
    lastModifiedBy: 'cb42921f-3b33-4efa-a873-4a1d86eb6caa',
    lastModifiedDate: '2024-09-16T12:38:03Z',
    requests: [
      {
        id: '8c33eb4e-9f32-411e-bb09-225615f0a266',
        responseId: '34500d92-10df-418b-b285-81cef7d0eb7a',
        reason: 'reason',
        amount: 5.0,
      },
    ],
    status: APPLICATION_STATUS.PENDING,
    firstNightCenter: true,
    requestedDate: '',
    requestedByFirstName: '',
    requestedByLastName: '',
    establishmentId: '',
  }

  user: BaseUser = {
    token: 'token',
    username: 'user',
    authSource: 'auth',
    userId: '608955ae-52ed-44cc-884c-011597a77949',
    name: 'name',
    displayName: 'Name',
    userRoles: [],
  }

  submitPrisonerAppData = {
    type: {
      value: 'PIN_PHONE_CREDIT_SWAP_VISITING_ORDERS',
      name: 'Swap visiting orders (VOs) for PIN credit',
      key: 'PIN_PHONE_CREDIT_SWAP_VISITING_ORDERS',
    },
    prisonerId: 'G4567',
    prisonerName: 'Emily Brown',
    group: {
      name: 'PIN phones',
      value: '1',
    },
    department: '343a7876-07b9-4ef8-947c-7cf554fae864',
    date: new Date('2024-09-15').toISOString(),
    additionalData: { details: 'Swap visiting orders (VOs) for PIN credit' },
  }

  appSearchPayload: ApplicationSearchPayload = {
    page: 1,
    size: 10,
    status: ['PENDING'],
    applicationTypes: null,
    requestedBy: null,
    assignedGroups: null,
  }

  appSearchResponse: ViewAppsListResponse = {
    page: 1,
    totalRecords: 3,
    exhausted: true,
    applicationTypes: {
      '1': { id: 1, name: 'Add new Social Contact', count: 1 },
      '2': { id: 2, name: 'Add new Official Contact', count: 0 },
      '3': { id: 3, name: 'Credit Swap Visiting Orders', count: 2 },
    },
    assignedGroups: [
      {
        id: '60d7303f-f6e5-4ffd-8ef1-769a52d00983',
        name: 'Business Hub',
        count: 3,
      },
      {
        id: '72c73234-b618-4c65-9fb1-6b710be68474',
        name: 'OMU',
        count: 0,
      },
    ],
    firstNightCenter: 3,
    apps: [
      {
        id: '1808f5e2-2bf4-499a-b79f-fb0a5f4bac7b',
        establishmentId: 'TEST_ESTABLISHMENT_FIRST',
        status: 'PENDING',
        appType: { id: 3, name: 'PIN_PHONE_CREDIT_SWAP_VISITING_ORDERS' },
        requestedBy: 'A12345',
        requestedByFirstName: 'John',
        requestedByLastName: 'Smith',
        createdDate: '2025-03-24T14:03:13Z',
        genericForm: false,
        assignedGroup: {
          id: '60d7303f-f6e5-4ffd-8ef1-769a52d00983',
          name: 'Business Hub',
          establishment: {
            id: 'TEST_ESTABLISHMENT_FIRST',
            name: 'ESTABLISHMENT_NAME_1',
            appTypes: [
              'PIN_PHONE_ADD_NEW_SOCIAL_CONTACT',
              'PIN_PHONE_ADD_NEW_OFFICIAL_CONTACT',
              'PIN_PHONE_CREDIT_SWAP_VISITING_ORDERS',
              'PIN_PHONE_SUPPLY_LIST_OF_CONTACTS',
              'PIN_PHONE_REMOVE_CONTACT',
              'PIN_PHONE_EMERGENCY_CREDIT_TOP_UP',
            ],
            defaultDepartments: false,
            blacklistedAppGroups: [],
            blacklistedAppTypes: [],
          },
          initialApp: 2,
          type: 'DEPARTMENT',
        },
      },
      {
        id: '53a02b48-b6af-47d5-9c54-3d0137f6ed96',
        establishmentId: 'TEST_ESTABLISHMENT_FIRST',
        status: 'PENDING',
        appType: { id: 3, name: 'PIN_PHONE_CREDIT_SWAP_VISITING_ORDERS' },
        requestedBy: 'A12345',
        requestedByFirstName: 'John',
        requestedByLastName: 'Smith',
        createdDate: '2025-03-23T14:03:13Z',
        genericForm: false,
        assignedGroup: {
          id: '60d7303f-f6e5-4ffd-8ef1-769a52d00983',
          name: 'Business Hub',
          establishment: {
            id: 'TEST_ESTABLISHMENT_FIRST',
            name: 'ESTABLISHMENT_NAME_1',
            appTypes: [
              'PIN_PHONE_ADD_NEW_SOCIAL_CONTACT',
              'PIN_PHONE_ADD_NEW_OFFICIAL_CONTACT',
              'PIN_PHONE_CREDIT_SWAP_VISITING_ORDERS',
              'PIN_PHONE_SUPPLY_LIST_OF_CONTACTS',
              'PIN_PHONE_REMOVE_CONTACT',
              'PIN_PHONE_EMERGENCY_CREDIT_TOP_UP',
            ],
            defaultDepartments: false,
            blacklistedAppGroups: [],
            blacklistedAppTypes: [],
          },
          initialApp: 3,
          type: 'DEPARTMENT',
        },
      },
      {
        id: 'b4e9944b-3a27-4d10-b12b-895426349ea3',
        establishmentId: 'TEST_ESTABLISHMENT_FIRST',
        status: 'PENDING',
        appType: { id: 3, name: 'PIN_PHONE_CREDIT_SWAP_VISITING_ORDERS' },
        requestedBy: 'A12345',
        requestedByFirstName: 'John',
        requestedByLastName: 'Smith',
        createdDate: '2025-03-21T14:03:13Z',
        genericForm: false,
        assignedGroup: {
          id: '60d7303f-f6e5-4ffd-8ef1-769a52d00983',
          name: 'Business Hub',
          establishment: {
            id: 'TEST_ESTABLISHMENT_FIRST',
            name: 'ESTABLISHMENT_NAME_1',
            appTypes: [
              'PIN_PHONE_ADD_NEW_SOCIAL_CONTACT',
              'PIN_PHONE_ADD_NEW_OFFICIAL_CONTACT',
              'PIN_PHONE_CREDIT_SWAP_VISITING_ORDERS',
              'PIN_PHONE_SUPPLY_LIST_OF_CONTACTS',
              'PIN_PHONE_REMOVE_CONTACT',
              'PIN_PHONE_EMERGENCY_CREDIT_TOP_UP',
            ],
            defaultDepartments: false,
            blacklistedAppGroups: [],
            blacklistedAppTypes: [],
          },
          initialApp: 3,
          type: 'DEPARTMENT',
        },
      },
    ],
  }

  comment: Comment = {
    id: '8980f68a-eabd-4b00-9ef3-a5d733da3a9f',
    appId: 'f4da49b9-f5d6-4931-9e81-aa6d69a12b2a',
    message: 'This is my first comment',
    prisonerNumber: 'G3682UE',
    createdDate: '2025-04-09T15:57:29Z',
    createdBy: {
      username: 'ZFAITHFULL_GEN',
      userId: '487900',
      fullName: 'Zak Faithfull',
      category: 'STAFF',
      establishment: {
        id: 'TEST_ESTABLISHMENT_FIRST',
        name: 'ESTABLISHMENT_NAME_1',
      },
    },
  }

  commentsResponse: CommentsResponse = {
    page: 1,
    totalElements: 1,
    exhausted: true,
    contents: [this.comment],
  }

  response: Response = {
    id: 'be0e8ede-aeb4-432f-b115-a57c39d1579b',
    prisonerId: 'G3682UE',
    appId: '991acfa4-39e9-4b08-b81c-cf5b95edd55e',
    reason: '',
    decision: 'APPROVED',
    createdDate: '2025-04-10T14:11:14.440791',
    createdBy: {
      username: 'ZFAITHFULL_GEN',
      userId: '487900',
      fullName: 'Zak Faithfull',
      category: 'STAFF',
      establishment: {
        id: 'TEST_ESTABLISHMENT_FIRST',
        name: 'ESTABLISHMENT_NAME_1',
      },
    },
    appliesTo: ['9242f1d0-3c4f-49f2-84e1-dcfefe5113d0'],
  }

  historyResponse: History[] = [
    {
      id: 'd8d267c0-42ac-42bf-a72f-2f826e1ee049',
      appId: '4d122405-27a1-4603-80cc-d7252a4e43ee',
      entityId: '1ebf7110-82cf-4dc1-b872-92c7d71847fc',
      entityType: 'ASSIGNED_GROUP',
      activityMessage: {
        header: 'Logged by Sweety John',
        body: 'Assigned to OMU',
      },
      createdDate: '2025-05-13T08:44:02Z',
    },
    {
      id: '26aae683-6dcb-432f-bf5d-f46752d809f1',
      appId: '4d122405-27a1-4603-80cc-d7252a4e43ee',
      entityId: '343a7876-07b9-4ef8-947c-7cf554fae864',
      entityType: 'ASSIGNED_GROUP',
      activityMessage: {
        header: 'Forwarded to group Business Hub by Sweety John',
        body: 'Assigned to BH',
      },
      createdDate: '2025-05-13T10:11:23Z',
    },
    {
      id: '1084ce95-b2f2-4e5e-8e49-9b60c0d5e643',
      appId: '4d122405-27a1-4603-80cc-d7252a4e43ee',
      entityId: '59927020-5141-4df8-baef-3f327397ed70',
      entityType: 'COMMENT',
      activityMessage: {
        header: 'Comment added by Sweety John',
      },
      createdDate: '2025-05-13T10:12:22Z',
    },
    {
      id: 'bca2a226-ef95-41ce-951d-dac63f2bb827',
      appId: '4d122405-27a1-4603-80cc-d7252a4e43ee',
      entityId: '973b3526-18d4-420d-a721-6345887680ee',
      entityType: 'RESPONSE',
      activityMessage: {
        header: 'Marked as declined by Sweety John',
      },
      createdDate: '2025-05-13T10:17:36Z',
    },
  ]

  supportedPrisonIds = ({ prisonIds = ['HEI', 'BLI'] } = {}): string[] => prisonIds

  assignedGroups: ViewApplicationsResponseAssignedGroup[] = [
    {
      id: '343a7876-07b9-4ef8-947c-7cf554fae864',
      name: 'Business Hub',
      count: 10,
    },
    {
      id: '2262b27d-ad93-43e2-98f9-542297135eb3',
      name: 'Chaplaincy',
      count: 0,
    },
    {
      id: '1ebf7110-82cf-4dc1-b872-92c7d71847fc',
      name: 'OMU',
      count: 10,
    },
    {
      id: '3db3fb1a-a542-419b-99e2-3d24009293b8',
      name: 'Safer Custody',
      count: 0,
    },
    {
      id: 'e9515b3e-8ad1-4029-b4fb-ac9a2474db34',
      name: 'Security',
      count: 0,
    },
  ]

  departments = [
    {
      id: '343a7876-07b9-4ef8-947c-7cf554fae864',
      name: 'Business Hub',
      establishment: {
        id: 'PNI',
        name: 'Preston (HMP)',
        appTypes: [1, 2, 3, 4],
      },
      initialApp: 'PIN_PHONE_SUPPLY_LIST_OF_CONTACTS',
      type: 'WING',
    },
    {
      id: '2262b27d-ad93-43e2-98f9-542297135eb3',
      name: 'Chaplaincy',
      establishment: {
        id: 'PNI',
        name: 'Preston (HMP)',
        appTypes: [1, 2, 3, 4],
      },
      initialApp: 'PIN_PHONE_ADD_NEW_SOCIAL_CONTACT',
      type: 'WING',
    },
  ]

  prisoner: InmateDetail = {
    offenderNo: 'A1234AA',
    bookingId: 432132,
    bookingNo: 'string',
    offenderId: 0,
    rootOffenderId: 0,
    firstName: 'string',
    middleName: 'string',
    lastName: 'string',
    dateOfBirth: '1970-03-15',
    age: 0,
    activeFlag: true,
    facialImageId: 0,
    agencyId: 'string',
    assignedLivingUnitId: 0,
    religion: 'string',
    language: 'string',
    interpreterRequired: true,
    writtenLanguage: 'string',
    alertsCodes: ['string'],
    activeAlertCount: 0,
    inactiveAlertCount: 0,
    alerts: [
      {
        alertId: 1,
        bookingId: 14,
        offenderNo: 'G3878UK',
        alertType: 'X',
        alertTypeDescription: 'Security',
        alertCode: 'XER',
        alertCodeDescription: 'Escape Risk',
        comment: 'Profession lock pick.',
        dateCreated: '2019-08-20',
        dateExpires: '2020-08-20',
        modifiedDateTime: '2021-07-05T10:35:17',
        expired: true,
        active: false,
        addedByFirstName: 'John',
        addedByLastName: 'Smith',
        expiredByFirstName: 'John',
        expiredByLastName: 'Smith',
      },
    ],
    assignedLivingUnit: {
      agencyId: 'string',
      locationId: 0,
      description: 'string',
      agencyName: 'string',
    },
    physicalAttributes: {
      sexCode: 'M',
      gender: 'Male',
      raceCode: 'W1',
      ethnicity: 'White: Eng./Welsh/Scot./N.Irish/British',
      heightFeet: 5,
      heightInches: 60,
      heightMetres: 1.76,
      heightCentimetres: 176,
      weightPounds: 50,
      weightKilograms: 67,
    },
    physicalCharacteristics: [
      {
        type: 'string',
        characteristic: 'string',
        detail: 'string',
        imageId: 0,
      },
    ],
    profileInformation: [
      {
        type: 'string',
        question: 'string',
        resultValue: 'string',
      },
    ],
    physicalMarks: [
      {
        type: 'string',
        side: 'string',
        bodyPart: 'string',
        orientation: 'string',
        comment: 'string',
        imageId: 0,
      },
    ],
    assessments: [
      {
        bookingId: 123456,
        offenderNo: 'GV09876N',
        classificationCode: 'C',
        classification: 'Cat C',
        assessmentCode: 'CATEGORY',
        assessmentDescription: 'Categorisation',
        cellSharingAlertFlag: true,
        assessmentDate: '2018-02-11',
        nextReviewDate: '2018-02-11',
        approvalDate: '2018-02-11',
        assessmentAgencyId: 'MDI',
        assessmentStatus: 'A',
        assessmentSeq: 1,
        assessmentComment: 'Comment details',
        assessorId: 130000,
        assessorUser: 'NGK33Y',
      },
    ],
    csra: 'string',
    csraClassificationCode: 'STANDARD',
    csraClassificationDate: '2025-07-23',
    category: 'string',
    categoryCode: 'string',
    birthPlace: 'WALES',
    birthCountryCode: 'GBR',
    inOutStatus: 'IN, OUT, TRN',
    identifiers: [
      {
        type: 'PNC',
        value: '1231/XX/121',
        offenderNo: 'A1234AB',
        bookingId: 1231223,
        issuedAuthorityText: 'Important Auth',
        issuedDate: '2018-01-21',
        caseloadType: 'GENERAL',
        whenCreated: '2021-07-05T10:35:17',
        offenderId: 234547,
        rootOffenderId: 654321,
      },
    ],
    personalCareNeeds: [
      {
        personalCareNeedId: 1,
        problemType: 'MATSTAT',
        problemCode: 'ACCU9',
        problemStatus: 'ON',
        problemDescription: 'Preg, acc under 9mths',
        commentText: 'a comment',
        startDate: '2010-06-21',
        endDate: '2010-06-21',
      },
    ],
    sentenceDetail: {
      sentenceExpiryDate: '2020-02-03',
      automaticReleaseDate: '2020-02-03',
      conditionalReleaseDate: '2020-02-03',
      nonParoleDate: '2020-02-03',
      postRecallReleaseDate: '2020-02-03',
      licenceExpiryDate: '2020-02-03',
      homeDetentionCurfewEligibilityDate: '2020-02-03',
      paroleEligibilityDate: '2020-02-03',
      homeDetentionCurfewActualDate: '2020-02-03',
      actualParoleDate: '2020-02-03',
      releaseOnTemporaryLicenceDate: '2020-02-03',
      earlyRemovalSchemeEligibilityDate: '2020-02-03',
      earlyTermDate: '2020-02-03',
      midTermDate: '2020-02-03',
      lateTermDate: '2020-02-03',
      topupSupervisionExpiryDate: '2020-02-03',
      tariffDate: '2020-02-03',
      dtoPostRecallReleaseDate: '2020-02-03',
      tariffEarlyRemovalSchemeEligibilityDate: '2020-02-03',
      effectiveSentenceEndDate: '2020-02-03',
      bookingId: 1234123,
      sentenceStartDate: '2010-02-03',
      additionalDaysAwarded: 5,
      automaticReleaseOverrideDate: '2020-02-03',
      conditionalReleaseOverrideDate: '2020-02-03',
      nonParoleOverrideDate: '2020-02-03',
      postRecallReleaseOverrideDate: '2020-04-01',
      dtoPostRecallReleaseDateOverride: '2020-04-01',
      nonDtoReleaseDate: '2020-04-01',
      sentenceExpiryCalculatedDate: '2020-02-03',
      sentenceExpiryOverrideDate: '2020-02-03',
      licenceExpiryCalculatedDate: '2020-02-03',
      licenceExpiryOverrideDate: '2020-02-03',
      paroleEligibilityCalculatedDate: '2020-02-03',
      paroleEligibilityOverrideDate: '2020-02-03',
      topupSupervisionExpiryCalculatedDate: '2020-02-03',
      topupSupervisionExpiryOverrideDate: '2020-02-03',
      homeDetentionCurfewEligibilityCalculatedDate: '2020-02-03',
      homeDetentionCurfewEligibilityOverrideDate: '2020-02-03',
      nonDtoReleaseDateType: 'CRD',
      confirmedReleaseDate: '2020-04-20',
      releaseDate: '2020-04-01',
      etdOverrideDate: '2019-04-02',
      etdCalculatedDate: '2019-04-02',
      mtdOverrideDate: '2019-04-02',
      mtdCalculatedDate: '2019-04-02',
      ltdOverrideDate: '2019-04-02',
      ltdCalculatedDate: '2019-04-02',
      homeDetentionCurfewEndDate: '2019-04-01',
      topupSupervisionStartDate: '2019-04-01',
    },
    offenceHistory: [
      {
        bookingId: 1123456,
        offenceDate: '2018-02-10',
        offenceRangeDate: '2018-03-10',
        offenceDescription: 'Commit an act / series of acts with intent to pervert the course of public justice',
        offenceCode: 'RR84070',
        statuteCode: 'RR84',
        mostSerious: true,
        primaryResultCode: 'string',
        secondaryResultCode: 'string',
        primaryResultDescription: 'string',
        secondaryResultDescription: 'string',
        primaryResultConviction: true,
        secondaryResultConviction: true,
        courtDate: '2018-02-10',
        caseId: 100,
        offenceSeverityRanking: 100,
        sentenceStartDate: '2018-03-10',
        primarySentence: true,
      },
    ],
    sentenceTerms: [
      {
        bookingId: 1132400,
        sentenceSequence: 2,
        termSequence: 1,
        consecutiveTo: 2,
        sentenceType: '2',
        sentenceTypeDescription: '2',
        startDate: '2018-12-31',
        years: 1,
        months: 2,
        weeks: 3,
        days: 4,
        lifeSentence: true,
        caseId: 'string',
        fineAmount: 0.1,
        sentenceTermCode: 'IMP',
        lineSeq: 1,
        sentenceStartDate: '2018-12-31',
      },
    ],
    aliases: [
      {
        title: 'Mr',
        firstName: 'Mike',
        middleName: 'John',
        lastName: 'Smith',
        age: 32,
        dob: '1980-02-28',
        gender: 'Male',
        ethnicity: 'Mixed: White and Black African',
        raceCode: 'M2',
        nameType: 'Alias Name',
        createDate: '2019-02-15',
        offenderId: 543548,
      },
    ],
    status: 'ACTIVE IN, INACTIVE OUT, INACTIVE TRN',
    statusReason: 'CRT-CA',
    lastMovementTypeCode: 'TAP, CRT, TRN, ADM, REL',
    lastMovementReasonCode: 'CA',
    lastMovementToAgency: {
      agencyId: 'MDI',
      description: 'Moorland (HMP & YOI)',
      longDescription: 'Moorland (HMP & YOI)',
      agencyType: 'INST',
      active: true,
      courtType: 'CC',
      courtTypeDescription: 'Crown Court',
      deactivationDate: '2012-01-12',
      addresses: [
        {
          addressId: 543524,
          addressType: 'BUS',
          flat: '3B',
          premise: 'Liverpool Prison',
          street: 'Slinn Street',
          locality: 'Brincliffe',
          town: 'Liverpool',
          townCode: '17743',
          postalCode: 'LI1 5TH',
          county: 'Herefordshire',
          countyCode: 'HEREFORD',
          country: 'England',
          countryCode: 'ENG',
          comment: 'This is a comment text',
          primary: true,
          mail: true,
          noFixedAddress: false,
          startDate: '2005-05-12',
          endDate: '2021-02-12',
          phones: [
            {
              phoneId: 2234232,
              number: '0114 2345678',
              type: 'TEL',
              ext: '123',
            },
          ],
          addressUsages: [
            {
              addressId: 23422313,
              addressUsage: 'HDC',
              addressUsageDescription: 'HDC Address',
              activeFlag: true,
            },
          ],
        },
      ],
      phones: [
        {
          phoneId: 2234232,
          number: '0114 2345678',
          type: 'TEL',
          ext: '123',
        },
      ],
    },
  }
}
