---
# Per environment values which override defaults in hmpps-managing-prisoner-apps-staff-ui/values.yaml

generic-service:
  ingress:
    host: managing-prisoner-apps-staff-ui.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: 'https://managing-prisoner-apps-staff-ui.hmpps.service.justice.gov.uk'
    HMPPS_AUTH_URL: 'https://sign-in.hmpps.service.justice.gov.uk/auth'
    TOKEN_VERIFICATION_API_URL: 'https://token-verification-api.prison.service.justice.gov.uk'
    COMPONENT_API_URL: 'https://frontend-components.hmpps.service.justice.gov.uk'
    DPS_URL: 'https://dps.prison.service.justice.gov.uk/'
    DPS_PRISONER_URL: 'https://prisoner.digital.prison.service.justice.gov.uk/'
    HMPPS_MANAGE_USERS_API_URL: 'https://manage-users-api.hmpps.service.justice.gov.uk'
    MANAGING_PRISONER_APPS_API_URL: 'https://managing-prisoner-apps-api.hmpps.service.justice.gov.uk'
    AUDIT_ENABLED: 'false'

generic-prometheus-alerts:
  alertSeverity: hmpps-launchpad
